"""Build the app favicon from the Codex hero illustration.

The source is a delicate pencil sketch: lovely at 130px on the map, an
unreadable smudge at 16px in a browser tab. Downscaling alone loses it, so the
strokes are first flattened to solid ink and dilated, which survives the
resample. The result sits on the app's paper colour so it reads on both light
and dark browser chrome.

The icons are emitted as base64 data URIs and inlined into index.html rather
than shipped as separate files, so the offline single-file build stays a
genuinely single file.

Usage:  python scripts/make_favicon.py     (then paste the URIs into index.html)
"""
from __future__ import annotations

import base64
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "assets" / "illustrations" / "hero-cover.png"
PAPER = (250, 247, 240)  # --paper
INK = (42, 42, 40)  # --ink

# (name, pixel size, stroke threshold, dilation passes)
# 32 covers browser tabs, 96 covers bookmarks and high-DPI. A 180px
# apple-touch-icon is deliberately omitted: ~24 KB of base64 inlined into every
# page load is a poor trade for an iOS home-screen-only icon.
TARGETS = [
    ("favicon-32", 32, 225, 2),
    ("favicon-96", 96, 225, 2),
]


def render(size: int, threshold: int, thicken: int, pad: float = 1.06) -> bytes:
    img = Image.open(SOURCE).convert("RGBA")
    # flatten onto white first: the source's transparency would otherwise
    # confuse the luminance threshold below
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.alpha_composite(img)
    grey = flat.convert("L")

    # trim the generous transparent margin so the mark fills the tile
    box = grey.point(lambda p: 255 if p < 245 else 0).getbbox()
    if box:
        grey = grey.crop(box)

    # solid strokes, then dilate (MinFilter grows dark regions) so hairlines
    # do not simply vanish when the image is resampled down to 16-32px
    mask = grey.point(lambda p: 0 if p < threshold else 255)
    for _ in range(thicken):
        mask = mask.filter(ImageFilter.MinFilter(3))

    side = int(max(mask.size) * pad)
    canvas = Image.new("L", (side, side), 255)
    canvas.paste(mask, ((side - mask.width) // 2, (side - mask.height) // 2))

    tile = ImageOps.colorize(canvas, black=INK, white=PAPER).resize((size, size), Image.LANCZOS)
    buf = BytesIO()
    tile.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


START = "<!-- favicon:start (generated by scripts/make_favicon.py — do not edit by hand) -->"
END = "<!-- favicon:end -->"


def main() -> None:
    links = []
    total = 0
    for name, size, threshold, thicken in TARGETS:
        png = render(size, threshold, thicken)
        uri = "data:image/png;base64," + base64.b64encode(png).decode("ascii")
        links.append(f'    <link rel="icon" type="image/png" sizes="{size}x{size}" href="{uri}" />')
        total += len(uri)
        print(f"{name:12s} {size:>3}x{size:<3} {len(png) / 1024:5.1f} KB png")

    index = ROOT / "index.html"
    html = index.read_text(encoding="utf-8")
    if START not in html or END not in html:
        raise SystemExit("index.html is missing the favicon:start/end markers")
    head, rest = html.split(START, 1)
    _, tail = rest.split(END, 1)
    index.write_text(f"{head}{START}\n" + "\n".join(links) + f"\n    {END}{tail}", encoding="utf-8")
    print(f"\ninlined {len(links)} icons into index.html (+{total / 1024:.1f} KB of base64)")


if __name__ == "__main__":
    main()
